iimage: jonaskello/docker-and-compose:1.12.1-1.8.0
services:
  - docker:1.12.1-dind

before_script:
  - docker info
  - docker-compose version

# We have two jobs, first, we lint the project with Rubocop to
# keep us honest and clean
rubocop:
  script:
    - docker-compose up -f docker-compose-ci.yml
    - rubocop

# Then we run our RSpec suite. When we run tests against
# Selenium, Rails will save screenshots of failures. We capture
# Them as artifacts so we can grab them through Gitlab's UI
# later.
rspec:
  script:
  - rspec spec
  artifacts:
    when: on_failure
    expire_in: 1 week
    paths:
    - tmp/screenshots/
    - log/