image: ruby:latest
cache:
  paths:
    - vendor/ruby

variables:
  RAILS_ENV: test
  POSTGRES_DB: test
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test-password

before_script:
  - apt-get update -qq && apt-get install -yqq nodejs libpq-dev
  - gem install bundler --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor

rails:
  services:
    - postgres:latest
  script:
    - bundle exec rake db:create db:schema:load
    - bundle exec rspec

rubocop:
  script:
    - bundle exec rubocop