image: docker
services:
  - docker:dind

before_script:
  - apk update
  - apk upgrade
  - apk add python python-dev py-pip build-base
  - pip install -U setuptools
  - apk add python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install --upgrade pip
  - pip install docker-compose

build_image:
  stage: build
  script:
    - docker-compose -f ./docker-compose-ci.yml build
  