image: ruby:2.6.3

variables:
  BUNDLE_CACHE: "vendor/bundle/"
  RAILS_ENV: "test"

cache:
  untracked: true
  key: "$CI_BUILD_NAME"
  paths:
    - vendor/bundle/

before_script:
  - bundle install --path vendor/bundle
  - bundle exec rake db:create
  - bundle exec rake db:migrate

stages:
  - test
  - code_analyser
  - audit

rspec:
  stage: test
  script:
    - bundle exec rspec

rubocop:
  stage: code_analyser
  script:
    - bundle exec rails generate rubocop_rails_config:install
    - bundle exec rubocop

brakeman:
  stage: audit
  script:
    - bundle exec brakeman
