# Run before each script
before_script:
  - gem install bundler
  - touch log/application.log
  - touch log/test.log
  - bundle install --jobs $(nproc) --path=/cache/bundler
  - cp config/database.gitlab-ci.yml config/database.yml
  - "bundle exec rake db:create RAILS_ENV=test"
  - "RAILS_ENV=test bundle exec rake db:reset"

job1:
    script: "bundle exec rspec"
    
