image: jonaskello/docker-and-compose:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  
build_image:
  stage: build
  script:
    - docker-compose -f ./docker-compose-ci.yml build
  