image: ruby:2.6.3

variables:
  BUNDLE_CACHE: "vendor/bundle/"
  RAILS_ENV: "test"

cache:
  untracked: true
  key: "$CI_BUILD_NAME"
  paths:
    - vendor/bundle/

before_script:
  - bundle install --path vendor/bundle
  - bundle exec rake db:create
  - bundle exec rake db:migrate

stages:
  - test
  - code_analyser
  - audit

rspec:
  stage: test
  script:
    - bundle exec rspec

rubocop:
  stage: code_analyser
  script:
    - bundle exec rails generate rubocop_rails_config:install
    - bundle exec rubocop

brakeman:
  stage: audit
  script:
    - bundle exec brakeman

sonarqube:
  stage: audit
  script: 
    - curl --insecure -o ./sonarscanner.zip -L "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip"
    - unzip sonarscanner.zip
    - ./sonar-scanner-4.2.0.1873-linux/bin/sonar-scanner -Dsonar.projectKey=sas_judo -Dsonar.sources=./app -Dsonar.host.url=http://sonarqube.localhost:9000 -Dsonar.login=0f5637ec7a1dfc79b1ea613803bb16002d74dd86
    - ./sonarqube-status.sh
