image: ruby:2.6.3

variables:
  BUNDLE_CACHE: "vendor/bundle/"
  RAILS_ENV: "test"
  DB_HOST: postgres
  DB_USERNAME: postgres
  DB_PASSWORD: ""

cache:
  untracked: true
  key: "$CI_BUILD_NAME"
  paths:
    - vendor/bundle/

services:
  - postgres:latest

before_script:
  - bundle install --path vendor/bundle
  - bundle exec rake db:create
  - bundle exec rake db:migrate

stages:
  - test

rspec:
  stage: test
  script:
    - bundle exec rspec

rubocop:
  stage: test
  script:
    - bundle exec rubocop

bundle-audit:
  stage: test
  script:
    - bundle exec bundle-audit update
    - bundle exec bundle-audit check