image: ruby:2.6.5

cache:
  paths:
    - vendor/bundle
    - node_modules

services:
  - postgres:10.1

variables:
  BUNDLE_PATH: vendor/bundle
  DISABLE_SPRING: 1
  DB_HOST: postgres

before_script:
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --quiet
  - bundle exec rake db:migrate --quiet
  - bundle exec rake db:test:prepare --quiet

  # Project setup
  - bundle check || bundle install --jobs $(nproc)
  - yarn install

  - cp config/database.yml.ci config/database.yml
  - bundle exec rails db:create RAILS_ENV=test
  - bundle exec rails db:schema:load RAILS_ENV=test
  - bundle exec webpack

stages:
  - test
  - lint
  - deploy

rspec:
  stage: test
  script:
      - rspec

brakeman:
  stage: test
  script:
    - bundle exec brakeman -z -q

rubocop:
  stage: lint
  script:
    - bundle exec rubocop

#

#Deploy Production:
  #stage: deploy
  #retry: 2
  #only:
  #  - master
  #script:
  #  - ./bin/setup_heroku
  #  - dpl --provider=heroku --app=awesome-app --api-key=$HEROKU_API_KEY
  #  - heroku run rake db:migrate --exit-code --app awesome-app
  #  - heroku run rake statics:seed --exit-code --app awesome-app

#Deploy Staging:
  #stage: deploy
  #allow_failure: true
  #retry: 2
  #except:
  #  - master
  #script:
  #  - ./bin/setup_heroku
  #  - dpl --provider=heroku --app=awesome-app-staging --api-key=$HEROKU_API_KEY
  #  - heroku run rake db:migrate --exit-code --app awesome-app-staging
  #  - heroku run rake statics:seed --exit-code --app awesome-app-staging