image: docker
services:
  - docker:dind

  before_script:
  - apk update
  - pip install -U setuptools
  - apk add python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install --upgrade pip
  - pip install docker-compose

build_image:
  stage: build
  script:
    - docker-compose -f ./docker/docker-compose-ci.yml build
  