image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose
  - docker-compose -f docker-compose-ci.yml build
  - docker-compose -f docker-compose-ci.yml up -d
  # here we can install our dependencies (composer, yarn…)

tests:
  script:
    # launch our tests
    - docker-compose exec web bundle exec rubocop