version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dev_password
    user: "${UID}:${GID}"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec foreman start -f Procfile.dev"
    volumes:
      - .:/myapp
      - ./vendor:/usr/local/bundle
    ports:
      - "6000:3000"
      - "6035:3035"
    depends_on:
      - db
    user: "${UID}:${GID}"
  

